### PR TITLE
X Remix, Lone Nights Addendums

### PR DESCRIPTION
**Pull request by sw5ciprl**
No, seriously - why don't brackets appear in the app?

### CODE REVIEW

**Comment by HemantSachdeva** [comment]
> No, seriously - why don't brackets appear in the app?

image

**Comment by sw5ciprl** [comment]
I used the || here. Might work, might not. Also {} are used in the config to open it. Might break smth.

**Comment by HemantSachdeva** [comment]
> I used the || here. Might work, might not. Also {} are used in the config to open it. Might break smth.

I Edited

**Comment by sw5ciprl** [comment]
I'll try this next time. Hopefully doesn't break anything lulz.

**Comment by HemantSachdeva** [comment]
> I'll try this next time. Hopefully doesn't break anything lulz.

Yeee
if breaks;
do
git commit --amend
done
;p

**Pull request merged**
